name: joint-crab

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy==0.8
  - python==3.6
  - ipython==6.5.0
  - jupyter==1.0.0
  - jupyterlab==0.34.12
  - cython==0.28.5
  - numpy==1.15.1
  - astropy==3.0.4
  - regions==0.3
  - click==7.0
  - pyyaml==3.13
  - scipy==1.1.0
  - reproject==0.4
  - uncertainties==3.0.2
  - naima==0.8.1
  - iminuit==1.3.3
  - sherpa==4.10
  - healpy==1.11.0
  - matplotlib>=2,<3
  - pandas==0.23.4
  - ruamel.yaml
  - pip:
    - multinorm
